var nameList = [
	"Time",
	"Past",
	"Future",
	"Dev",
	"Fly",
	"Flying",
	"Soar",
	"Soaring",
	"Power",
	"Falling",
	"Fall",
	"Jump",
	"Cliff",
	"Mountain",
	"Rend",
	"Red",
	"Blue",
	"Green",
	"Yellow",
	"Gold",
	"Demon",
	"Demonic",
	"Panda",
	"Cat",
	"Kitty",
	"Kitten",
	"Zero",
	"Memory",
	"Trooper",
	"XX",
	"Bandit",
	"Fear",
	"Light",
	"Glow",
	"Tread",
	"Deep",
	"Deeper",
	"Deepest",
	"Mine",
	"Your",
	"Worst",
	"Enemy",
	"Hostile",
	"Force",
	"Video",
	"Game",
	"Donkey",
	"Mule",
	"Colt",
	"Cult",
	"Cultist",
	"Magnum",
	"Gun",
	"Assault",
	"Recon",
	"Trap",
	"Trapper",
	"Redeem",
	"Code",
	"Script",
	"Writer",
	"Near",
	"Close",
	"Open",
	"Cube",
	"Circle",
	"Geo",
	"Genome",
	"Germ",
	"Spaz",
	"Shot",
	"Echo",
	"Beta",
	"Alpha",
	"Gamma",
	"Omega",
	"Seal",
	"Squid",
	"Money",
	"Cash",
	"Lord",
	"King",
	"Duke",
	"Rest",
	"Fire",
	"Flame",
	"Morrow",
	"Break",
	"Breaker",
	"Numb",
	"Ice",
	"Cold",
	"Rotten",
	"Sick",
	"Sickly",
	"Janitor",
	"Camel",
	"Rooster",
	"Sand",
	"Desert",
	"Dessert",
	"Hurdle",
	"Racer",
	"Eraser",
	"Erase",
	"Big",
	"Small",
	"Short",
	"Tall",
	"Sith",
	"Bounty",
	"Hunter",
	"Cracked",
	"Broken",
	"Sad",
	"Happy",
	"Joy",
	"Joyful",
	"Crimson",
	"Destiny",
	"Deceit",
	"Lies",
	"Lie",
	"Honest",
	"Destined",
	"Bloxxer",
	"Hawk",
	"Eagle",
	"Hawker",
	"Walker",
	"Zombie",
	"Sarge",
	"Capt",
	"Captain",
	"Punch",
	"One",
	"Two",
	"Uno",
	"Slice",
	"Slash",
	"Melt",
	"Melted",
	"Melting",
	"Fell",
	"Wolf",
	"Hound",
	"Legacy",
	"Sharp",
	"Dead",
	"Mew",
	"Chuckle",
	"Bubba",
	"Bubble",
	"Sandwich",
	"Smasher",
	"Extreme",
	"Multi",
	"Universe",
	"Ultimate",
	"Death",
	"Ready",
	"Monkey",
	"Elevator",
	"Wrench",
	"Grease",
	"Head",
	"Theme",
	"Grand",
	"Cool",
	"Kid",
	"Boy",
	"Girl",
	"Vortex",
	"Paradox",
];

export function generateRandomNames() {
	return nameList[Math.floor(Math.random() * nameList.length)];
}

var chatMessages = [
	"This is gold 😂",
	"I'm crying laughing 🤣",
	"Bro stop it 💀",
	"Not today satan 😭",
	"Tell me lies 😏",
	"Say less fam 💯",
	"Big brain time 🧠",
	"Small brain moment 🤏",
	"My guy really said 👀",
	"Who hurt you 💀",
	"Sir this is Wendy's 🍔",
	"Ma'am this is Walmart 🛒",
	"Plot twist incoming 👀",
	"I felt that one 😭",
	"Me at 3am 🌙",
	"Nobody asked but okay 👍",
	"That's enough internet today 💀",
	"Touch some grass 🌱",
	"Go outside please 🌞",
	"Average day in Ohio 💀",
	"Living rent free 🏠",
	"Mind sharing the brain cell? 🧠",
	"My turn with the brain cell 🔄",
	"Must be nice 🙃",
	"We get it you vape 💨",
	"Ok boomer go off 👴",
	"Calm down Karen ✋",
	"Let me speak to manager 📞",
	"Thoughts and prayers 🙏",
	"Prayer circle for this 🙌",
	"Circle gets the square 🔲",
	"Square up bro 👊",
	"Come at me bro 😤",
	"Back to the shadow realm 🌑",
	"Yeeted into oblivion 🚀",
	"This ain't it chief 👮",
	"Delete this nephew 🗑️",
	"Take my strong hand ✋",
	"Jebaited by life 🎣",
	"Perfectly balanced as all things ⚖️",
	"I understood that reference 👨‍💻",
	"Too soon man too soon ⏰",
	"Living in 3025 📅",
	"They don't know something 🤫",
	"We don't talk about that 🤐",
	"Spill the tea sis ☕",
	"Gossip girl vibes 🗽",
	"XOXO gossip girl 💋",
	"Who dis new person 👤",
	"New who dis 👁️",
	"Shadowbanned for what ❓",
	"Ratioed by a bot 🤖",
	"Losing braincells daily 📉",
	"Brain cell count zero 🔋",
	"Send help and snacks 🍕",
	"Bring pizza or don't come 🍕",
	"Taco Tuesday anyone? 🌮",
	"Wednesday my dudes 🐸",
	"Friday night vibes 🎉",
	"Sunday scaries hitting hard 😰",
	"Monday again already 😩",
	"Sleep is for the weak 😴",
	"Coffee first talk later ☕",
	"Need caffeine immediately ⚡",
	"Zero batteries charged today 🔋",
	"Running on fumes only ⛽",
	"Out of spoons today 🥄",
	"Mental capacity overload ⚠️",
	"Brain full go away 🚫",
	"Too many notifications 📱",
	"Stop mentioning me bro 🔔",
	"Leave me on read 📖",
	"Double text much? ✌️",
	"Delivered but not read 📧",
	"Seen 2 hours ago 👁️",
	"Typing for 10 minutes ⌨️",
	"Message too long didn't read 📚",
	"TL;DR version please 📝",
	"Summary in 5 words? 🤔",
	"That's what she said 😏",
	"Too easy come on 😎",
	"Challenge accepted let's go 💪",
	"Hold my beer watch this 🍺",
	"Hold my monster energy 🥫",
	"Hold my red bull 🐂",
	"Wings not included ✈️",
	"Red bull gives me wings 🦅",
	"Monster gives me nightmares 👹",
	"Gamer fuel activated 🎮",
	"Pro gamer move detected 🕹️",
	"Console wars are silly 🎯",
	"PC master race reporting 🖥️",
	"Potato PC loading screen 🥔",
	"Loading please wait... 💀",
	"Error 404 brain not found 🔍",
	"Page not found buddy 📄",
	"Connection timed out again 🌐",
	"Buffering... forever and ever 🔄",
	"Lag spikes are real 📈",
	"Ping higher than my grades 📊",
	"Packet loss is real 📦",
	"Rubberbanding back to reality 🏓",
	"Glitch in the matrix 🕳️",
	"Living in a simulation 🖥️",
	"Red pill or blue pill 💊",
	"Take the blue pill 💙",
	"Morpheus is that you? 🕶️",
	"Follow the white rabbit 🐇",
	"Down the rabbit hole 🕳️",
	"Alice in chains 🎸",
	"Unplug me from matrix 🔌",
	"Wake me up inside 😴",
	"Can't wake up fr 💤",
	"Sleep paralysis demon 👹",
	"Demon under my bed 🛏️",
	"Monster in my closet 👕",
	"Shadow people watching me 👥",
	"Gaslight gatekeep girlboss 💅",
	"Slay queen work it 👑",
	"Yasss kween slay 💁‍♀️",
	"Periodt dot com 💅",
	"And I oop- 😳",
	"Sksksksk and I oop 🔁",
	"VSCO girl in wild 🌊",
	"Save the turtles 🐢",
	"I said what I said 💅",
	"No take backs ever ❌",
	"Return policy expired 📅",
	"No refunds exchanges only 🔄",
	"All sales are final 💸",
	"You get what you get 🎁",
	"Don't complain about it 🤷",
	"First world problems 🙄",
	"Rich people issues 💰",
	"Broke boy summer coming ☀️",
	"Bank account crying 💸",
	"Wallet on life support 🏥",
	"Credit score in shambles 📉",
	"Financially unstable but happy 😃",
	"Money can't buy happiness 💵",
	"But it buys tacos though 🌮",
	"Tacos solve everything 🌮",
	"Burrito > everything else 🌯",
	"Pizza is a vegetable 🍕",
	"Fruit on pizza? 🤢",
	"Pineapple belongs in trash 🗑️",
	"Anchovies are war crimes 🐟",
	"Olives are little grapes 🫒",
	"Raisins are sad grapes 🍇",
	"Grapes are just wine babies 🍷",
	"Wine is just adult juice 🍷",
	"Beer is liquid bread 🍞",
	"Bread makes everything better 🥖",
	"Carbs are life honestly 🍝",
	"Keto diet starts Monday 📅",
	"Diet starts tomorrow I swear 📆",
	"Cheat day everyday whoops 😋",
	"Gym membership unused again 🏋️",
	"New year new me they said 🎆",
	"Same me different year 🥲",
	"Growth is painful sometimes 🌱",
	"Character development arc happening 📖",
	"Main character energy today ✨",
	"Side quests are better 🗺️",
	"Grinding irl everyday 📈",
	"Level up slowly but surely ⬆️",
	"Experience points gained slowly 📊",
	"Skill issue honestly get good 🎯",
	"Get gud scrub they said 🧼",
	"Git gud at life please 🖥️",
	"Touch grass and heal 🌿",
	"Go outside breathe air 🌬️",
	"Vitamin D deficiency who? ☀️",
	"Pasty white gang represent 🤍",
	"Sunburnt in 10 minutes 🔥",
	"Lobster mode activated 🦞",
	"Crispy bacon status achieved 🥓",
	"Well done steak energy 🥩",
	"Medium rare or nothing 🍖",
	"Burnt to a crisp oops 🔥",
	"Fire department on speed dial 📞",
	"Arson is illegal they said 🚒",
	"Jail time not included 👮",
	"Free my boy he didn't 🗽",
	"Justice for my homie ⚖️",
	"Free my mans wrongfully accused 🆓",
	"Blame it on the dog 🐕",
	"Dog ate my homework 📝",
	"Cat stepped on keyboard 🐈",
	"Keyboard malfunction sorry guys ⌨️",
	"Fat fingers tiny phone 📱",
	"Autocorrect sabotaged me again 🤖",
	"Typo intended for effect ✍️",
	"Grammar police incoming 👮‍♂️",
	"Spelling bee champion here 🐝",
	"English major trigger warning 📚",
	"Oxford comma matters change my mind 🔍",
	"Serial killer vibes without comma 🔪",
	"Let's eat grandma vs grandma 👵",
	"Punctuation saves lives fr 🚑",
	"Commas are important people 🔫",
	"Words have meaning apparently 📖",
	"Reading comprehension zero today 📉",
	"Literally dying of laughter 💀",
	"Figuratively speaking of course 🗣️",
	"Metaphorically in pain right now 😫",
	"Hyperbole is my love language ❤️",
	"Sarcasm font needed immediately ✒️",
	"I can't even right now 🚫",
	"I'm so done with this 🏁",
	"Checkered flag waving goodbye 🏳️",
	"Peace out cub scout ✌️",
	"Later skater boi 🛹",
	"Cya later alligator 🐊",
	"After while crocodile 🐊",
	"See ya soon raccoon 🦝",
	"Bye bye butterfly 🦋",
	"Adios amigos mi gente 👋",
	"Auf wiedersehen goodbye friends 🌍",
	"Sayonara suckers later days 👋",
	"I'm out peace and blessings ☮️",
	"Out like a light bulb 💡",
	"Off like a prom dress 👗",
	"Gone like yesterday's news 📰",
	"Vanished like my motivation 💨",
	"Disappeared like my will to live 😵",
	"Poof gone like my paycheck 💰",
	"Vamooshed into thin air 🌬️",
];

export function generateRandomStrings() {
	return chatMessages[Math.floor(Math.random() * chatMessages.length)];
}

export const findPrime = (num) => {
	let i,
		primes = [2, 3],
		n = 5;
	const isPrime = (n) => {
		let i = 1,
			p = primes[i],
			limit = Math.ceil(Math.sqrt(n));
		while (p <= limit) {
			if (n % p === 0) {
				return false;
			}
			i += 1;
			p = primes[i];
		}
		return true;
	};
	for (i = 2; i <= num; i += 1) {
		while (!isPrime(n)) {
			n += 2;
		}
		primes.push(n);
		n += 2;
	}
	return primes[num - 1];
};
